"""empty message

Revision ID: ad7ec4e9e455
Revises: 
Create Date: 2018-04-22 19:18:47.466253

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ad7ec4e9e455'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classes_date'), 'classes', ['date'], unique=False)
    op.create_index(op.f('ix_classes_title'), 'classes', ['title'], unique=False)
    op.create_table('performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qnum', sa.Integer(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qnum', sa.Integer(), nullable=True),
    sa.Column('widget', sa.String(length=128), nullable=True),
    sa.Column('type', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=1028), nullable=True),
    sa.Column('enum', sa.String(length=256), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_data_notes', table_name='data')
    op.drop_table('data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('notes', mysql.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_data_notes', 'data', ['notes'], unique=False)
    op.drop_table('questions')
    op.drop_table('performance')
    op.drop_index(op.f('ix_classes_title'), table_name='classes')
    op.drop_index(op.f('ix_classes_date'), table_name='classes')
    op.drop_table('classes')
    # ### end Alembic commands ###
